Align dev
pagopa/interop-probing-k8s pull request #6
Opened 2023-05-16 15:52 UTC by alessio-creo

2023-06-07 07:53 UTC, micdes-pagopa commented on overlays/prod/probing-scheduler/kustomization.yaml
> +- ../../../base/deplyment
Typo

2023-06-14 12:54 UTC, micdes-pagopa commented on overlays/dev/probing-api/deployment.yaml
Since the XRay daemon is used in all deployments, can you put it in the base? Same for the `AWS_XRAY_DAEMON_ADDRESS` env

2023-06-14 12:54 UTC, micdes-pagopa commented on overlays/prod/common/kustomization.yaml
> +namespace: dev
Be careful, this is a `prod` overlay. I see this mistake in many files in this PR. Same for some `uat` overlays.

2023-06-15 14:23 UTC, alessio-creo commented on overlays/dev/probing-api/deployment.yaml
I've put the xray container in the base. Can't find a way for env in specific container

2023-06-16 11:00 UTC, micdes-pagopa requested changes
Cannot merge the PR due to conflicts with `main` branch. Please fix

2023-06-16 14:51 UTC, alessio-creo commented
> Cannot merge the PR due to conflicts with `main` branch. Please fix

Done

2023-06-23 06:42 UTC, micdes-pagopa commented
Please don't include changes for uat/prod in this PR. There are currently 107 files changed and it's way too much for a single review.
You can open separate PRs for uat/prod once the configuration has been validated on dev.

2023-06-26 12:22 UTC, merged